config/routes.rb
ThirdProj::Application.routes.draw do
  root to: 'welcome#index'

  get "welcome/index"
  get "/login" => "welcome#new"
  post "/login" => "welcome#create"
  get "/logout" => "welcome#destroy"
  get "/users/:id/encounters" => "users#encounter"
  post "/users/:id/encounters" => "users#new_encounter"
  resources :users
  resources :partners do
    resources :encounters
  end
  resources :pronouns, only: [:index, :new, :create]
  resources :parts, only: [:index, :new, :create]
  resources :prefs
  resources :instruments, only: [:index, :new, :create]
  resources :contacts
  resources :sti_tests

end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  name            :string(255)
#  email           :string(255)
#  password_digest :string(255)
#  pref_id         :integer
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#

class User < ActiveRecord::Base
  attr_accessible :name, :email, :password, :password_confirmation, :pref_attributes
  has_many :encounters, through: :partners
  has_many :partners
  has_many :sti_tests
  belongs_to :pref
  has_secure_password
  validates :name, :email, :password, :password_confirmation, :presence => true
  validates :email, :uniqueness => true
  accepts_nested_attributes_for :pref

  def pronoun
    if self.pref_id
      return self.pref.pronoun
    else
      return nil
    end
  end

  def risk
    if self.encounters.any?
      @risk = 0
      self.encounters.each do |encounter|
        @risk += encounter.risk
      end
      @risk /= self.encounters.length
      if @risk <= 4
        return @risk = "low"
      elsif @risk <= 8
        return @risk = "medium"
      else
        return @risk = "high"
      end
    else
      return @risk = "we need more info to calculate that"
    end
  end
  def partners_at_risk
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    if session[:user_id]
      redirect_to "/users/#{session[:user_id]}"
    else
      redirect_to "/login"
    end
  end
  def new
    @user = User.new
    @pref = @user.build_pref
    @pronouns = Pronoun.all
    @email = params[:email]
    @password = params[:password]
  end
  def create
    @user = User.new(params[:user])
    if @user.save
      session[:user_id] = @user.id
      redirect_to user_path(@user)
    else
      redirect_to new_user_path
    end
  end
  def show
    @user = User.find(session[:user_id])
    @partners = @user.partners
    @encounters = @user.encounters.order("took_place DESC")
    @diseases = Disease.all.map do |disease|
      [disease.name, disease.risk_window(session[:user_id])]
    end
  end
  def edit
    @user = User.find(params[:id])
    if @user.pref_id
      @pref = @user.pref
      @pronoun = @user.pronoun
    else
      @pref = @user.build_pref
      @pronoun = Pronoun.first
    end
    @pronouns = Pronoun.all
  end
  def update
    @user = User.find(params[:id])
    if @user.update_attributes(params[:user])
      redirect_to user_path(@user)
    else
      redirect_to edit_user_path
    end
  end
  def destroy
    @user = User.find(params[:id])
    @user.destroy
  end
  def encounter
    @user = User.find(params[:id])
    @partners = @user.partners
    @encounters = @user.encounters.order("took_place DESC")
  end
  def new_encounter
    partner_id = params[:partner_id]
    redirect_to "/partners/#{partner_id}/encounters/new"
  end
end

app/views/users/edit.html.erb
<div class="dashes hidden to-hide"></div>
<div class="center">
  <%= form_for @user do |t| %>
  <%= t.label :name %>
  <%= t.text_field :name, value: @user.name %><br>
  <%= t.label :email, "Username" %>
  <%= t.text_field :email, value: @user.email %><br>
  <%= t.fields_for :pref do |f| %>
    <br><h2>Preferences</h2>
    <%= f.label :genital_name, "What do you call your genitals?", value: @pref.genital_name %>
    <%= f.text_field :genital_name %><br>
    <%= f.label :anus_name, "What do you call your anus?" %>
    <%= f.text_field :anus_name, value: @pref.anus_name %><br>
    <%= f.label :pronoun_id, "What pronouns do you use?" %>
    <%= f.select :pronoun_id, options_from_collection_for_select(@pronouns, :id, :subject, @pronoun.id) %>
    <% end %><br>
    <br>
  <%= t.label :password, "Re-enter password" %>
  <%= t.password_field :password %><br>
  <%= t.label :password_confirmation %>
  <%= t.password_field :password_confirmation %>
  <%= t.submit %>
  <% end %></div>

app/views/users/encounter.html.erb
<div class="dashes hidden to-hide"></div>
<div class="center">
  <h2>Recent Encounters:</h2>
    <ul>
      <li><% @encounters.each do |encounter| %>
          <br><%= link_to encounter.took_place, partner_encounter_path(encounter.partner, encounter) %>: <br>
          <%= encounter.partner.name %><br>
          Risk level:
          <% if encounter.risk <= 4 %>
            <span class="low">low</span>
          <% elsif encounter.risk <= 8 %>
            <span class="medium">medium</span>
          <% else %>
            <span class="high">high</span>
          <% end %><br>
        <% end %>
      </li>
    </ul>
    <br>
    <%= form_tag %>
    New Encounter with:
    <%= select_tag :partner_id, options_from_collection_for_select(@partners, :id, :name), id: "partner-select" %>
    <%= submit_tag "create", id: "new-encounter" %>
  </div>

app/views/users/new.html.erb
<div class="dashes hidden to-hide"></div>
<div class="center">
  <%= form_for @user do |t| %>
  <%= t.label :name %>
  <%= t.text_field :name %><br>
  <%= t.label :email, "Username" %>
  <%= t.text_field :email, value: @email %><br>
  <%= t.label :password %>
  <%= t.password_field :password, value: @password %><br>
  <%= t.label :password_confirmation %>
  <%= t.password_field :password_confirmation %>
  <br>
  <br>
  <%= t.fields_for :pref do |f| %>
    <h2>Preferences:</h2>
    <%= f.label :genital_name, "What do you call your genitals?" %>
    <%= f.text_field :genital_name %><br>
    <%= f.label :anus_name, "What do you call your anus?" %>
    <%= f.text_field :anus_name %><br>
    <%= f.label :pronoun_id, "What pronouns do you use?" %>
    <%= f.select :pronoun_id, options_from_collection_for_select(@pronouns, :id, :subject) %>
    <% end %>
    <br>
  <%= t.submit %>
  <% end %></div>

app/views/users/new_encounter.html.erb
<div class="center">
  <%= form_for [@partner, @encounter] do |t|%>
  <%= t.label :partner_id %>
  <%= t.select :partner_id, options_from_collection_for_select(@partners, :id, :name) %>
  <%= t.date_select :took_place %><br>
  self-assessed risk: <%= t.select :self_risk, options_for_select([1, 2, 3, 4, 5, 6, 7, 8, 9, 10]) %><br>
  <%= t.text_area :notes %><br>
    <% @instruments.each do |instrument| %>
    <% if @user.pref_id %>
      <% if instrument.part == "genitals" %>
        <%= "my #{@user.pref.genital_name} came in contact with " %>
      <% elsif instrument.part == "anus" %>
        <%= "my #{@user.pref.anus_name} came in contact with" %>
      <% else %>
        <%= "my #{instrument.part} came in contact with " %>
      <% end %>
    <% else %>
      <%= "my #{instrument.part} came in contact with " %>
    <% end %>
    <% if @partner.pref_id %>
      <%= @partner.pronoun.possessive %><br>
    <% else %>
      <%= "their" %><br>
    <% end %>
      <% @instruments.each do |inst| %>
        <%= t.fields_for :contacts do |builder| %>
          <%= builder.check_box :partner_instrument, {}, inst.id, nil %>
          <% if @partner.pref_id %>
            <% if inst.part == "genitals" %>
              <%= @partner.pref.genital_name %>
            <% elsif inst.part == "anus" %>
              <%= @partner.pref.anus_name  %>
            <% else %>
              <%= inst.part %>
            <% end %>
          <% else %>
            <%= inst.part %>
          <% end %>
          <%= builder.hidden_field :user_instrument, value: "#{instrument.id}" %>
          <%= builder.check_box :barriers %> with a barrier <br>
        <% end %>
      <% end %>
    <% end %>
    <%= t.check_box :fluid, value: true %>fluid exchange not accounted for (e.g. ejaculate in eyes, nose, or open cuts)<br>
  <%= t.submit %>
  <% end %>
</div>

app/views/users/show.html.erb
<div class="right">
  <div id="wrapper">
    <h2>Recent Encounters:</h2>
    <ul class="encounters">
      <% @encounters.each do |encounter| %>
      <% if encounter.risk <= 4 %>
            <li class="low">
          <% elsif encounter.risk <= 8 %>
            <li class="medium">
          <% else %>
            <li class="high">
          <% end %>
          <span class="normal">
          <%= link_to encounter.took_place, partner_encounter_path(encounter.partner, encounter) %> <br>
          <%= encounter.partner.name %>
        <% end %>
        <br>
        </span>
      </li>
    </ul>
    <br>
    <%= form_tag "/users/#{@user.id}/encounters" %>
    New Encounter with:
    <%= select_tag :partner_id, options_from_collection_for_select(@partners, :id, :name), id: "partner-select" %>
    <%= submit_tag "create", id: "new-encounter" %>
  </div>
</div>
<div class="dashes"></div>
<div class="center">
  <h1><%= "#{@user.name}" %>
    <% if @user.pref_id %>
      <%= " (#{@user.pronoun.subject})" %></h1> <br>
    <% end %>
  Average risk:

    <span class=<%=@user.risk%>><%= @user.risk %></span>
  <br><br>
  <% @diseases.each do |disease| %>
    <% if disease[1] %>
      <strong><%= disease[0] %></strong> risk window began:
        <%=" #{disease[1].strftime('%m/%d/%Y')}" %>
      <% else %>
        No test data for <strong><%= disease[0] %></strong>; consider getting tested.
    <% end %><br>
    <br>
  <% end %>
  <%= link_to "edit", edit_user_path(@user) %><br>
</div>