config/routes.rb
ThirdProj::Application.routes.draw do
  root to: 'welcome#index'

  get "welcome/index"
  get "/login" => "welcome#new"
  post "/login" => "welcome#create"
  get "/logout" => "welcome#destroy"
  get "/users/:id/encounters" => "users#encounter"
  post "/users/:id/encounters" => "users#new_encounter"
  resources :users
  resources :partners do
    resources :encounters
  end
  resources :pronouns, only: [:index, :new, :create]
  resources :parts, only: [:index, :new, :create]
  resources :prefs
  resources :instruments, only: [:index, :new, :create]
  resources :contacts
  resources :sti_tests

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link href='http://fonts.googleapis.com/css?family=Lily+Script+One|Londrina+Outline|Fanwood+Text' rel='stylesheet' type='text/css'>
  <title>RisqueFactr</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div id="container">
    <div class="nav">

          <div id="logo">
            <a href="/">
                Risque<span>Factr</span>
            </a>
          </div>
        <ul><% if session[:user_id] %>
            <li>
              <%= link_to "Dash", "/users" %><br>
            </li>
            <li><%= link_to "Partners", "/partners" %></li>
            <li><%= link_to "Tests", sti_tests_path %></li>
            <li>
              <%= link_to "Encounters", "/users/#{session[:user_id]}/encounters" %>
            </li>
            <li>
              <%= link_to "Log Out", "/logout"%><br>
            </li>
          <% else %>
            <li><%= link_to "Sign Up", new_user_path %></li>
          <% end %></ul>
      </div>
    <%= yield %>
  </div>
</body>
<link rel="stylesheet" href="https://d345spfe4d65od.cloudfront.net/static/tourmyapp/v1/tourmyapp.css" type="text/css">
<script type="text/javascript" src="https://d345spfe4d65od.cloudfront.net/static/tourmyapp/v1/tourmyapp.js"></script>

  <script type="text/javascript">
  var tour;
  jQuery(document).ready(function() {
      tour = new TourMyApp("592e253e8a039c92f574da21caa07cf7"); // REPLACE WITH YOUR ACCOUNT TOKEN
      tour.start("532298efbc1fbe2d840013ba");
  });
  </script>
</html>